env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
    no-console: 0,
    import/extensions: 0,
    no-param-reassign: 0,
    no-plusplus: 0,
    import/prefer-default-export: 0
}
